"""
Purpose: Interactive setup wizard for first-time RLMY configuration.
Usage: Called automatically on first run if no config exists.
Key Components: run_wizard() - interactive prompts using rich
Conventions: Creates ~/.config/rlmy/config.toml with user-provided model strings.
"""

from pathlib import Path
from textwrap import dedent
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from rich.markdown import Markdown


# Reference table of popular models (rendered as markdown)
MODEL_REFERENCE_TABLE = """
**Example Models** (any DSPy-compatible model string works):

| Provider  | Tier              | Model String                                    |
|-----------|-------------------|-------------------------------------------------|
| Bedrock   | High              | `bedrock/us.anthropic.claude-opus-4-6-v1`       |
| Bedrock   | Mid (recommended) | `bedrock/us.anthropic.claude-sonnet-4-5-v1:0`   |
| Bedrock   | Low               | `bedrock/us.anthropic.claude-haiku-4-5-v1:0`    |
| OpenAI    | High              | `openai/gpt-5.5`                                |
| OpenAI    | Mid               | `openai/gpt-4o-mini`                            |
| Groq      | High              | `groq/openai/gpt-oss-120b`                      |
| Groq      | Low               | `groq/openai/gpt-oss-20b`                       |
| Gemini    | High              | `gemini/gemini-3.5-flash`                       |
| Gemini    | Low               | `gemini/gemini-3.1-flash-lite`                  |

The **main model** is your strategist (plans, writes code).
The **sub model** runs inside the REPL for `llm_query()` calls (can be same or cheaper).
"""


def run_wizard(config_dir: Path, config_file: Path) -> bool:
    """
    Run interactive setup wizard to create config.toml.
    
    Args:
        config_dir: Path to ~/.config/rlmy/
        config_file: Path to ~/.config/rlmy/config.toml
    
    Returns:
        bool: True if config was created successfully, False if cancelled
    """
    console = Console()
    
    console.print()
    console.print(Panel.fit(
        dedent("""
            [bold blue]🚀 Welcome to RLMY![/bold blue]

            Which AI model would you like to use?
            (You can change this later in ~/.config/rlmy/config.toml)
        """).strip(),
        title="Model Selection"
    ))
    console.print()
    
    # Check if config already exists
    if config_file.exists():
        console.print(f"[yellow]⚠️  Config already exists: {config_file}[/yellow]")
        console.print()
        overwrite = Confirm.ask("Overwrite existing configuration?", default=False)
        if not overwrite:
            console.print("[dim]Setup cancelled.[/dim]")
            return False
        console.print()
    
    # Show model reference table
    console.print(Markdown(MODEL_REFERENCE_TABLE))
    console.print()
    
    # Prompt for main model
    main_model = Prompt.ask(
        "[bold]Main model[/bold]",
        default="bedrock/us.anthropic.claude-opus-4-8"
    ).strip()
    
    # Prompt for sub model
    sub_model = Prompt.ask(
        "[bold]Sub model[/bold] (press Enter to reuse main)",
        default=""
    ).strip()
    
    # If sub model is empty, use main model
    if not sub_model:
        sub_model = main_model
        console.print(f"[dim]→ Using {main_model} for both[/dim]")
    
    console.print()
    
    # Create config directory and file
    config_dir.mkdir(parents=True, exist_ok=True)
    
    config_content = dedent(f"""
        # RLMY Configuration
        # Generated by setup wizard

        [llm]
        main_model = "{main_model}"
        sub_model = "{sub_model}"

        # Note: Set credentials via environment variables:
        # - For Anthropic models: export ANTHROPIC_API_KEY='sk-ant-...'
        # - For Bedrock models: configure AWS credentials (aws configure)
        # - For OpenAI models: export OPENAI_API_KEY='sk-...'
        # - For Groq models: export GROQ_API_KEY='gsk_...'
        # - For Gemini models: export GEMINI_API_KEY='...'

        # To override via environment:
        # export RLM_MAIN_MODEL='your-model'
        # export RLM_SUB_MODEL='your-model'
    """).strip() + "\n"
    
    config_file.write_text(config_content)
    
    console.print(Panel.fit(
        dedent(f"""
            [green]✓ Configuration saved![/green]

            Location: {config_file}
        """).strip(),
        title="Setup Complete"
    ))
    console.print()
    
    # Show next steps based on main model provider
    console.print("[bold]📋 Next Steps[/bold]")
    console.print()
    
    if "bedrock" in main_model:
        console.print(dedent("""
            1. Configure AWS credentials:
               [cyan]aws configure[/cyan]

               Or set environment variables:
               [cyan]export AWS_PROFILE='your-profile'[/cyan]
        """).strip())
    elif "groq" in main_model:
        console.print(dedent("""
            1. Get a Groq API key:
               https://console.groq.com/keys

            2. Set the environment variable:
               [cyan]export GROQ_API_KEY='gsk_...'[/cyan]
        """).strip())
    elif "openai" in main_model:
        console.print(dedent("""
            1. Get an OpenAI API key:
               https://platform.openai.com/api-keys

            2. Set the environment variable:
               [cyan]export OPENAI_API_KEY='sk-...'[/cyan]
        """).strip())
    elif "gemini" in main_model:
        console.print(dedent("""
            1. Get a Gemini API key:
               https://aistudio.google.com/apikey

            2. Set the environment variable:
               [cyan]export GEMINI_API_KEY='...'[/cyan]
        """).strip())
    else:
        console.print("[dim]Set up credentials as needed for your provider.[/dim]")
    
    console.print()
    console.print(dedent("""
        3. Run RLMY:
           [cyan]rlmy[/cyan]
    """).strip())
    console.print()
    
    return True
